# Generated by Django 5.0.6 on 2024-06-02 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoguardian", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todo",
            name="completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="recurrence_interval_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="recurrence_interval_unit",
            field=models.CharField(
                blank=True,
                choices=[("d", "Day"), ("w", "Week"), ("m", "Month"), ("y", "Year")],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="recurrence_strict_interval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todo",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
