# Generated by Django 5.0.6 on 2024-06-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "todoguardian",
            "0002_todo_completed_todo_completion_date_todo_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="Completed?"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                    ("K", "K"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("O", "O"),
                    ("P", "P"),
                    ("Q", "Q"),
                    ("R", "R"),
                    ("S", "S"),
                    ("T", "T"),
                    ("U", "U"),
                    ("V", "V"),
                    ("W", "W"),
                    ("X", "X"),
                    ("Y", "Y"),
                    ("Z", "Z"),
                ],
                help_text="Priority is ordered from high to low (with A being the higgest priority).",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="recurrence_interval_number",
            field=models.IntegerField(
                blank=True,
                help_text="The interval used (a whole integer number).",
                null=True,
                verbose_name="Interval",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="recurrence_interval_unit",
            field=models.CharField(
                blank=True,
                choices=[("d", "Day"), ("w", "Week"), ("m", "Month"), ("y", "Year")],
                help_text="The unit for the selected interval: day, week, month or year.",
                max_length=1,
                verbose_name="Interval unit",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="recurrence_strict_interval",
            field=models.BooleanField(
                default=False,
                help_text="When selected the new due date will be calculated based on the existing due date, otherwise the completion date will be used to calculate the new due date.",
                verbose_name="Strict recurrence interval?",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Optional. In case this is set it will be used to hide a todo until it can start. In case of postponing or recurrence this date will also be used to calculate the respective new start date (relevant to the other dates).",
                null=True,
            ),
        ),
    ]
