# Generated by Django 5.0.6 on 2024-06-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoguardian", "0004_alter_todo_recurrence_interval_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="recurrence_interval_number",
            field=models.IntegerField(
                blank=True,
                help_text="The interval used (a whole integer number).",
                null=True,
                verbose_name="Interval",
            ),
        ),
    ]
