# Generated by Django 5.0.6 on 2024-06-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoguardian", "0005_alter_todo_recurrence_interval_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoOld",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                            ("M", "M"),
                            ("N", "N"),
                            ("O", "O"),
                            ("P", "P"),
                            ("Q", "Q"),
                            ("R", "R"),
                            ("S", "S"),
                            ("T", "T"),
                            ("U", "U"),
                            ("V", "V"),
                            ("W", "W"),
                            ("X", "X"),
                            ("Y", "Y"),
                            ("Z", "Z"),
                        ],
                        help_text="Priority is ordered from high to low (with A being the higgest priority).",
                        max_length=1,
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Completed?"),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "recurrence_strict_interval",
                    models.BooleanField(
                        default=False,
                        help_text="When selected the new due date will be calculated based on the existing due date, otherwise the completion date will be used to calculate the new due date.",
                        verbose_name="Strict recurrence interval?",
                    ),
                ),
                (
                    "recurrence_interval_number",
                    models.IntegerField(
                        blank=True,
                        help_text="The interval used (a whole integer number).",
                        null=True,
                        verbose_name="Interval",
                    ),
                ),
                (
                    "recurrence_interval_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("d", "Day"),
                            ("w", "Week"),
                            ("m", "Month"),
                            ("y", "Year"),
                        ],
                        help_text="The unit for the selected interval: day, week, month or year.",
                        max_length=1,
                        verbose_name="Interval unit",
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional. In case this is set it will be used to hide a todo until it can start. In case of postponing or recurrence this date will also be used to calculate the respective new start date (relevant to the other dates).",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="todo",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="completion_date",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="created",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="description",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="recurrence_interval_number",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="recurrence_interval_unit",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="recurrence_strict_interval",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="start_date",
        ),
    ]
