# Generated by Django 5.0.6 on 2024-06-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "todoguardian",
            "0007_todo_completed_todo_completion_date_todo_created_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="completed",
        ),
    ]
