# Generated by Django 5.0.6 on 2024-06-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoguardian", "0008_remove_todo_completed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TodoOld",
        ),
    ]
