# Generated by Django 5.0.6 on 2024-06-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoguardian", "0010_todo_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="completed",
        ),
        migrations.AddField(
            model_name="todo",
            name="_completed",
            field=models.BooleanField(default=False, verbose_name="completed?"),
        ),
    ]
