# Generated by Django 5.0.6 on 2024-06-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoguardian", "0013_project_alter_todo_recurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="projects",
            field=models.ManyToManyField(
                related_name="todos", to="todoguardian.project"
            ),
        ),
    ]
