# Generated by Django 5.0.6 on 2024-06-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoguardian", "0014_todo_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="todos", to="todoguardian.project"
            ),
        ),
    ]
