# Generated by Django 5.0.6 on 2024-06-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoguardian", "0015_alter_todo_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="todo",
            name="contexts",
            field=models.ManyToManyField(
                blank=True, related_name="todos", to="todoguardian.context"
            ),
        ),
    ]
