# Generated by Django 5.0.6 on 2024-06-15 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoguardian", "0016_context_todo_contexts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
