# Generated by Django 5.0.6 on 2024-06-16 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoguardian", "0018_annotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="todo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="todoguardian.todo",
            ),
        ),
    ]
