# Generated by Django 5.0.6 on 2024-06-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoguardian", "0019_alter_annotation_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
