# Generated by Django 5.0.6 on 2024-06-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoguardian", "0020_context_slug_project_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="context",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slug",
        ),
    ]
